### ISSUE TITLE
How RTL works?

### ISSUE THREAD

**Issue by zraees** [hasangilak/react-multilingual#1]
Dear Hasan,

I am trying to use react-multilingual, I have one issue, which is related to direction, I tried and translation showing up without any glitch but RTL is not working, maybe I am missing something !!! 
one more thing, In your GIT there is no 'en.css' and 'fa.css' we need to create it? if yes in which directory we'll save?

**Comment by hasangilak** [comment]
I see. I`ll fix the repo (example and readme) for tonight. thanks for your report.

**Comment by thg303** [comment]
is it fixed now??

**Comment by hasangilak** [comment]
I`ll check this again for tonight. I`m darn busy these days

**Comment by thg303** [comment]
I can go for a PR for this if you don't mind. cssLazyLoading needs some clean up too

**Comment by hasangilak** [comment]
yeah. it would be great.

**Comment by hasangilak** [comment]
@thg303 thanks :+1:
